<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Menu extends Model
{
    use HasFactory;
    protected $table = 'menus';
    protected $fillable = [
      'parent_id',
      'name',
      'url',
      'slug',
      'icon_path'
    ];
    protected $hidden = ['created_at', 'updated_at'];
    public function parentMenu(){
        return $this->belongsTo(Menu::class, 'parent_id');
    }

    public function childs():HasMany{
        return $this->hasMany(Menu::class, 'parent_id');
    }

    public function deleteSubMenus(){
        foreach ($this->childs() as $child) {
            $child->deleteSubMenus();
            $child->delete();
        }
    }

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($menu){
            $menu->deleteSubMenus();
        });
    }
}
